In [32]:
import numpy as np

In [33]:
np.__version__

'2.3.1'

In [34]:
#list,array
lst =[1,2,3,4,5]
arr =np.array(lst)

In [35]:
np.zeros((5,20))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [36]:
arr =np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [37]:
#1d array convert into 2d
arr=np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [38]:
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [39]:
arr.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [40]:
arr =np.random.randint(1,5,9)
arr

array([1, 3, 3, 4, 4, 2, 3, 4, 1], dtype=int32)

In [41]:
arr =np.random.randint(1,5,(3,3))
arr

array([[2, 3, 3],
       [4, 1, 1],
       [4, 4, 1]], dtype=int32)

In [42]:
arr =np.random.random(10)
arr

array([0.83686841, 0.46394562, 0.07511934, 0.46782698, 0.28169025,
       0.2506843 , 0.45368422, 0.38474444, 0.24719042, 0.75359718])

In [43]:
arr =np.random.random((5,10))
arr

array([[0.16293289, 0.95148671, 0.12525895, 0.80256891, 0.13084067,
        0.1828442 , 0.02049936, 0.2368478 , 0.06350295, 0.6916593 ],
       [0.47462262, 0.34262839, 0.92418066, 0.5186442 , 0.01620165,
        0.62118687, 0.44811432, 0.87700023, 0.07369189, 0.20763282],
       [0.2741545 , 0.17024041, 0.24865425, 0.7959014 , 0.58559011,
        0.80987241, 0.25673178, 0.59724484, 0.40091782, 0.5409047 ],
       [0.50716249, 0.46846973, 0.97239375, 0.31010684, 0.94378309,
        0.4315525 , 0.0926068 , 0.41477532, 0.70516254, 0.58939352],
       [0.89829773, 0.95472727, 0.22912595, 0.46140598, 0.96120325,
        0.90411202, 0.02918418, 0.0567398 , 0.57386634, 0.10457152]])

In [44]:
arr =np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [45]:
print("shape of array :-",arr.shape)
print("size of array :-",arr.size)
print("data types :-",arr.dtype)
print("number of dimension",arr.ndim)

shape of array :- (12, 5)
size of array :- 60
data types :- int64
number of dimension 2


In [46]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [47]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [48]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [49]:
arr.shape

(12, 5)

In [50]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [51]:
arr.T.shape

(5, 12)

In [52]:
arr =np.arange(30)

In [53]:
arr[0]=100

In [54]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [58]:
arr =np.arange(60).reshape(12,5)

In [59]:
arr[1,3:5]

array([8, 9])

In [60]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [61]:
arr[1,1]=100

In [62]:
arr

array([[  0,   1,   2,   3,   4],
       [  5, 100,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [63]:
arr[11,4]

np.int64(59)

In [64]:
arr[-1][-1]

np.int64(59)

In [65]:
arr[11][-1]

np.int64(59)

In [67]:
arr =np.array(np.arange(225).reshape(5,15,3))

In [68]:
arr.ndim,arr.shape,arr.size,arr.dtype

(3, (5, 15, 3), 225, dtype('int64'))

In [69]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [71]:
arr[0,2:,2]

array([ 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [72]:
arr[0,3:5] 

array([[ 9, 10, 11],
       [12, 13, 14]])

In [73]:
arr[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [74]:
arr[0,0:1,0:1]

array([[0]])

In [75]:
arr[0,1,1]=1000

In [77]:
arr[0,1,1]

np.int64(1000)

In [78]:
arr =np.array([1,2,3,4,4,5])

In [79]:
arr

array([1, 2, 3, 4, 4, 5])

In [80]:
arr/2

array([0.5, 1. , 1.5, 2. , 2. , 2.5])

In [81]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,5,3,4,5])

In [82]:
arr1-arr2

array([ 0, -3,  0,  0,  0])